version: "2"
services:
  php:
    build: .
    container_name: web
    ports:
      - "80:80"
      - "9000:9000"
    links:
      - db
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./html:/usr/share/nginx/html"
      - "./var/log/:/var/log/nginx/"
      - "./etc/php/7.0/:/etc/php/7.0/"
    stdin_open: true
    tty: true
    cap_add:
      - ALL

  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"